/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.components;

/**
 *
 * @author dragonyte
 */
public class CardIngredientWhitManagerView extends javax.swing.JPanel {

    /**
     * Creates new form CardProductView
     */
    public CardIngredientWhitManagerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtImage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnLess = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtQuantity = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnPlus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtUnit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 221));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setForeground(new java.awt.Color(51, 102, 255));

        txtImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/cheese-solid-24.png"))); // NOI18N
        jPanel5.add(txtImage);

        jPanel3.add(jPanel5);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        txtName.setBackground(new java.awt.Color(102, 102, 102));
        txtName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setText("Name");
        jPanel1.add(txtName);

        jPanel4.add(jPanel1);

        jPanel6.setForeground(new java.awt.Color(51, 102, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        btnLess.setBackground(new java.awt.Color(51, 102, 255));
        btnLess.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btnLess.setForeground(new java.awt.Color(255, 255, 255));
        btnLess.setText("-");
        btnLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLessActionPerformed(evt);
            }
        });
        jPanel8.add(btnLess);

        jPanel6.add(jPanel8, java.awt.BorderLayout.WEST);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel9.setLayout(new java.awt.GridLayout(2, 0));

        txtQuantity.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        txtQuantity.setText("0");
        txtQuantity.setBorder(null);
        jPanel9.add(txtQuantity);

        jPanel6.add(jPanel9, java.awt.BorderLayout.CENTER);

        btnPlus.setBackground(new java.awt.Color(51, 102, 255));
        btnPlus.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setText("+");
        jPanel7.add(btnPlus);

        btnAdd.setBackground(new java.awt.Color(51, 102, 255));
        btnAdd.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText(">");
        jPanel7.add(btnAdd);

        jPanel10.add(jPanel7);

        jPanel6.add(jPanel10, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel6);

        jPanel2.setForeground(new java.awt.Color(51, 102, 255));

        txtUnit.setBackground(new java.awt.Color(102, 102, 102));
        txtUnit.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        txtUnit.setForeground(new java.awt.Color(102, 102, 102));
        txtUnit.setText("Unit");
        jPanel2.add(txtUnit);

        jPanel4.add(jPanel2);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnLess;
    public javax.swing.JButton btnPlus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel txtImage;
    public javax.swing.JLabel txtName;
    public javax.swing.JTextField txtQuantity;
    public javax.swing.JLabel txtUnit;
    // End of variables declaration//GEN-END:variables
}
