/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.components;

/**
 *
 * @author dragonyte
 */
public class CardReceipView extends javax.swing.JPanel {

    /**
     * Creates new form CardReceipView
     */
    public CardReceipView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLess = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        txtUnit = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCurrentQuantity = new javax.swing.JLabel();

        txtName.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        txtName.setText("Name");
        add(txtName);

        btnLess.setText("-");
        jPanel1.add(btnLess);

        txtQuantity.setText("0");
        jPanel1.add(txtQuantity);

        btnPlus.setText("+");
        jPanel1.add(btnPlus);

        add(jPanel1);

        txtUnit.setText("Unidad");
        add(txtUnit);

        btnSave.setText(">");
        add(btnSave);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabel3.setText("Disponible");
        jPanel2.add(jLabel3);

        txtCurrentQuantity.setText("Quantity");
        jPanel2.add(txtCurrentQuantity);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLess;
    public javax.swing.JButton btnPlus;
    public javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel txtCurrentQuantity;
    public javax.swing.JLabel txtName;
    public javax.swing.JTextField txtQuantity;
    public javax.swing.JLabel txtUnit;
    // End of variables declaration//GEN-END:variables
}
