/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.components;

/**
 *
 * @author dragonyte
 */
public class CardReceipInfoView extends javax.swing.JPanel {

    /**
     * Creates new form CardReceipInfoView
     */
    public CardReceipInfoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtQuantity = new javax.swing.JTextField();
        txtUnit = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnDrop = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtName.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        txtName.setText("Name");
        jPanel1.add(txtName);

        add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(txtQuantity);

        txtUnit.setText("Unidad");
        jPanel3.add(txtUnit);

        add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnDrop.setText("X");
        jPanel5.add(btnDrop);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDrop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel txtName;
    public javax.swing.JTextField txtQuantity;
    public javax.swing.JLabel txtUnit;
    // End of variables declaration//GEN-END:variables
}
