/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.components;

/**
 *
 * @author dragonyte
 */
public class CardTableView extends javax.swing.JPanel {

    /**
     * Creates new form CardTableView
     */
    public CardTableView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNumber = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSell = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnEdit.setBackground(new java.awt.Color(51, 102, 255));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/pencil-regular-24.png"))); // NOI18N
        jPanel1.add(btnEdit);

        jPanel5.add(jPanel1, java.awt.BorderLayout.NORTH);

        txtNumber.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/knife-regular-24.png"))); // NOI18N
        txtNumber.setText("1");
        jPanel2.add(txtNumber);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        btnSell.setBackground(new java.awt.Color(51, 102, 255));
        btnSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSell.setText("Vender");
        jPanel3.add(btnSell);

        jPanel6.add(jPanel3);

        btnPay.setBackground(new java.awt.Color(51, 102, 255));
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Pagar");
        jPanel4.add(btnPay);

        jPanel6.add(jPanel4);

        jPanel5.add(jPanel6, java.awt.BorderLayout.SOUTH);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnPay;
    public javax.swing.JButton btnSell;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JLabel txtNumber;
    // End of variables declaration//GEN-END:variables
}
