/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.components;

/**
 *
 * @author dragonyte
 */
public class CardUserView extends javax.swing.JPanel {

    /**
     * Creates new form CardUserView
     */
    public CardUserView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnnnnnn = new javax.swing.JPanel();
        txtAdmin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtMail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        txtAdmin.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        txtAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtAdmin.setText("Admin");
        pnnnnnn.add(txtAdmin);

        jPanel1.add(pnnnnnn);

        btnEdit.setBackground(new java.awt.Color(51, 102, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/pencil-regular-24.png"))); // NOI18N
        jPanel5.add(btnEdit);

        btnDelete.setBackground(new java.awt.Color(51, 102, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/eraser-solid-24.png"))); // NOI18N
        jPanel5.add(btnDelete);

        jPanel1.add(jPanel5);

        add(jPanel1);

        txtName.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setText("Name");
        jPanel2.add(txtName);

        add(jPanel2);

        txtMail.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        txtMail.setForeground(new java.awt.Color(153, 153, 153));
        txtMail.setText("Email");
        jPanel3.add(txtMail);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnnnnnn;
    public javax.swing.JLabel txtAdmin;
    public javax.swing.JLabel txtMail;
    public javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
