/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.inventory;

import java.awt.Dimension;

/**
 *
 * @author dragonyte
 */
public class IngredientView extends javax.swing.JPanel {

    /**
     * Creates new form IngredientView
     */
    public IngredientView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        pnnn1234 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnIngredients = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCreate.setBackground(new java.awt.Color(102, 153, 255));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("+");
        jPanel1.add(btnCreate);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtSearch.setText("Buscar");
        jPanel3.add(txtSearch);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pnnn1234.setBackground(new java.awt.Color(204, 204, 204));
        pnnn1234.setForeground(new java.awt.Color(204, 255, 204));
        pnnn1234.setLayout(new javax.swing.BoxLayout(pnnn1234, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnIngredients.setPreferredSize(new Dimension(400,pnIngredients.getMaximumSize().height));
        jScrollPane1.setViewportView(pnIngredients);

        pnnn1234.add(jScrollPane1);

        jPanel2.add(pnnn1234, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCreate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pnIngredients;
    public javax.swing.JPanel pnnn1234;
    public javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
