/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.menu;

/**
 *
 * @author dragonyte
 */
public class AcountingMenu extends javax.swing.JPanel {

    /**
     * Creates new form AcountingMenu
     */
    public AcountingMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExpens = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnBills = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnAnnulments = new javax.swing.JButton();
        PaymentMethods = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(6, 0));

        btnExpens.setText("Gastos");
        add(btnExpens);

        btnSell.setText("Ventas");
        add(btnSell);

        btnBills.setText("Facturas");
        add(btnBills);

        btnReports.setText("Informes");
        add(btnReports);

        btnAnnulments.setText("Cancelaciones");
        add(btnAnnulments);

        PaymentMethods.setText("Metodos de pago");
        add(PaymentMethods);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton PaymentMethods;
    public javax.swing.JButton btnAnnulments;
    public javax.swing.JButton btnBills;
    public javax.swing.JButton btnExpens;
    public javax.swing.JButton btnReports;
    public javax.swing.JButton btnSell;
    // End of variables declaration//GEN-END:variables
}
