/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.menu;

/**
 *
 * @author dragonyte
 */
public class AcountingMenu extends javax.swing.JPanel {

    /**
     * Creates new form AcountingMenu
     */
    public AcountingMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExpens = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnBills = new javax.swing.JButton();
        btnAnnulments = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnTips = new javax.swing.JButton();
        btnPaymentMethod = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(7, 0));

        btnExpens.setBackground(new java.awt.Color(102, 153, 255));
        btnExpens.setForeground(new java.awt.Color(255, 255, 255));
        btnExpens.setText("Gastos");
        add(btnExpens);

        btnSell.setBackground(new java.awt.Color(102, 153, 255));
        btnSell.setForeground(new java.awt.Color(255, 255, 255));
        btnSell.setText("Ventas");
        add(btnSell);

        btnBills.setBackground(new java.awt.Color(102, 153, 255));
        btnBills.setForeground(new java.awt.Color(255, 255, 255));
        btnBills.setText("Facturas");
        add(btnBills);

        btnAnnulments.setBackground(new java.awt.Color(102, 153, 255));
        btnAnnulments.setForeground(new java.awt.Color(255, 255, 255));
        btnAnnulments.setText("Cancelaciones");
        add(btnAnnulments);

        btnReports.setBackground(new java.awt.Color(102, 153, 255));
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Informes adicionales");
        add(btnReports);

        btnTips.setBackground(new java.awt.Color(102, 153, 255));
        btnTips.setForeground(new java.awt.Color(255, 255, 255));
        btnTips.setText("Propinas");
        add(btnTips);

        btnPaymentMethod.setBackground(new java.awt.Color(102, 153, 255));
        btnPaymentMethod.setForeground(new java.awt.Color(255, 255, 255));
        btnPaymentMethod.setText("Metodos de pago");
        add(btnPaymentMethod);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAnnulments;
    public javax.swing.JButton btnBills;
    public javax.swing.JButton btnExpens;
    public javax.swing.JButton btnPaymentMethod;
    public javax.swing.JButton btnReports;
    public javax.swing.JButton btnSell;
    public javax.swing.JButton btnTips;
    // End of variables declaration//GEN-END:variables
}
