/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.menu;

/**
 *
 * @author dragonyte
 */
public class SellMenu extends javax.swing.JPanel {

    /**
     * Creates new form SellMenu
     */
    public SellMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTable = new javax.swing.JButton();
        btnRoom = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        btnTable.setBackground(new java.awt.Color(102, 153, 255));
        btnTable.setForeground(new java.awt.Color(255, 255, 255));
        btnTable.setText("Mesas");
        add(btnTable);

        btnRoom.setBackground(new java.awt.Color(102, 153, 255));
        btnRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnRoom.setText("Habitaciones");
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });
        add(btnRoom);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRoom;
    public javax.swing.JButton btnTable;
    // End of variables declaration//GEN-END:variables
}
