/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.accounting;

/**
 *
 * @author dragonyte
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnGraph = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        pnTable = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        pnGraph.setBackground(new java.awt.Color(255, 255, 255));
        pnGraph.setLayout(new javax.swing.BoxLayout(pnGraph, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(pnGraph);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        txtTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtTotal.setText("Total");
        jPanel5.add(txtTotal);

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Dinero en caja");
        jPanel5.add(jLabel1);

        jPanel4.add(jPanel5);

        btnEdit.setBackground(new java.awt.Color(102, 153, 255));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/pencil-regular-24.png"))); // NOI18N
        jPanel4.add(btnEdit);

        btnX.setBackground(new java.awt.Color(102, 153, 255));
        btnX.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnX.setForeground(new java.awt.Color(255, 255, 255));
        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointofsale/images/x-regular-24.png"))); // NOI18N
        jPanel4.add(btnX);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnTable.setBackground(new java.awt.Color(255, 255, 255));
        pnTable.setLayout(new javax.swing.BoxLayout(pnTable, javax.swing.BoxLayout.LINE_AXIS));
        add(pnTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JPanel pnGraph;
    public javax.swing.JPanel pnTable;
    public javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
