/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pointofsale.views.accounting;

/**
 *
 * @author dragonyte
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnGraph = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        pnTable = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        pnGraph.setLayout(new javax.swing.BoxLayout(pnGraph, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(pnGraph);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        txtTotal.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txtTotal.setText("Total");
        jPanel5.add(txtTotal);

        jLabel1.setText("Dinero en caja");
        jPanel5.add(jLabel1);

        jPanel4.add(jPanel5);

        btnEdit.setText("E");
        jPanel4.add(btnEdit);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnTable.setLayout(new javax.swing.BoxLayout(pnTable, javax.swing.BoxLayout.LINE_AXIS));
        add(pnTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JPanel pnGraph;
    public javax.swing.JPanel pnTable;
    public javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
